#!/usr/bin/env python3
"""Dump Zipf word frequencies for the Lettermelt word-list build.

Why this exists
---------------
Deciding whether a word is "common" is the single hardest judgement in the
word lists, and spell-checker tiers get it badly wrong in both directions:
"lath" sits in an early tier while "gator" sits in a late one, which is the
opposite of how often anyone actually meets those words.

Zipf frequency (log10 of occurrences per billion words, roughly 1-8) ranks
them correctly, so it is the primary signal. The data lives in the Python
`wordfreq` package, but the word-list build is Node, so this script writes the
frequencies out once and the build reads the file. That keeps `npm` builds
runnable without a Python toolchain.

Usage
-----
    pip install wordfreq
    python3 scripts/dump_word_zipf.py

Writes scripts/data/word-zipf.txt: one "word zipf" pair per line, sorted, for
every candidate word at or above ZIPF_FLOOR. Anything below the floor is far
too rare to ever be a required word, so leaving it out keeps the file small.
"""

import json
import os
import subprocess
import sys

ZIPF_FLOOR = 2.0
MIN_LEN, MAX_LEN = 4, 11

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(ROOT, "scripts", "data")
OUT_FILE = os.path.join(OUT_DIR, "word-zipf.txt")

# The candidate set is exactly what the build considers: real dictionary words
# that also appear in the graded spell-check lists (which filters lowercase
# proper-noun artifacts such as "eric" and "texas").
CANDIDATE_JS = r"""
const en = require('an-array-of-english-words');
const d = require('wordlist-english');
const tiers = {};
for (const k of Object.keys(d)) {
  if (!/^english(\/american)?\/\d+$/.test(k)) continue;
  const t = Number(k.match(/(\d+)$/)[1]);
  (d[k] || []).forEach(w => {
    const l = String(w).toLowerCase();
    if (!(l in tiers) || tiers[l] > t) tiers[l] = t;
  });
}
const out = [];
for (const w of en) {
  const l = String(w).toLowerCase();
  if (/^[a-z]+$/.test(l) && l.length >= MIN_LEN && l.length <= MAX_LEN && l in tiers) out.push(l);
}
process.stdout.write(JSON.stringify(Array.from(new Set(out))));
"""


def main():
    try:
        from wordfreq import zipf_frequency
    except ImportError:
        sys.exit("wordfreq is not installed. Run: pip install wordfreq")

    script = CANDIDATE_JS.replace("MIN_LEN", str(MIN_LEN)).replace("MAX_LEN", str(MAX_LEN))
    proc = subprocess.run(["node", "-e", script], cwd=ROOT, capture_output=True, text=True)
    if proc.returncode != 0:
        sys.exit("could not list candidate words (are the npm word packages installed?)\n" + proc.stderr)
    words = json.loads(proc.stdout)

    rows = []
    for word in words:
        zipf = zipf_frequency(word, "en")
        if zipf >= ZIPF_FLOOR:
            rows.append((word, zipf))
    rows.sort()

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_FILE, "w", encoding="utf-8") as handle:
        handle.write("# word zipf — generated by scripts/dump_word_zipf.py (wordfreq, Apache-2.0)\n")
        handle.write("# Zipf frequency: log10 occurrences per billion words. Floor %.1f.\n" % ZIPF_FLOOR)
        for word, zipf in rows:
            handle.write("%s %.2f\n" % (word, zipf))

    print("scanned %d candidates, wrote %d words >= %.1f -> %s"
          % (len(words), len(rows), ZIPF_FLOOR, os.path.relpath(OUT_FILE, ROOT)))


if __name__ == "__main__":
    main()
